apiVersion: v1
kind: Pod
metadata:
  name: webapp-sample
spec:
  containers:
    - name: webapp-sample
      image: webapp
      envFrom:
#taken from confimap-file.yaml file
        - configMapRef:
             name: app-config