apiVersion: batch/v1
kind: Job
metadata:
  name: math-job
spec:
  template:
    spec:
     containers:
     - image: ubuntu
       name: math-job-ubuntu
       command: ["expr","3","+","4"]
     restartPolicy: Never