apiVersion: v1
kind: Pod
metadata:
  name: livenessProbe-sample
  labels:
    name: simple-webapp
spec:
  containers:
  - image: kodekloud/webapp-delayed-start
    imagePullPolicy: Always
    name: simple-webapp
    livenessProbe:
       httpGet:
        path: /live
        port: 8080
       periodSeconds: 1
       initialDelaySeconds: 80
    ports:
    - containerPort: 8080
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File