apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: drupal-mysql
  name: drupal-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal-mysql
  template:
    metadata:
      labels:
        app: drupal-mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: mysql_USERNAME
          valueFrom:
           secretKeyRef:
            name: drupal-mysql-secret
            key: MYSQL_USER
        - name: mysql_PASSWORD
          valueFrom:
           secretKeyRef:
            name: drupal-mysql-secret
            key: MYSQL_ROOT_PASSWORD
        - name: mysql_DB
          valueFrom:
           secretKeyRef:
            name: drupal-mysql-secret
            key: MYSQL_DATABASE
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-vol
          subPath: dbdata
      volumes:
        - name: mysql-vol
          persistentVolumeClaim:
             claimName: drupal-mysql-pvc