apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: webapp
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: app
            operator: In
            values:
            - Large    
  containers:
    - name: webapp
      image: webapp