apiVersion: v1
kind: Pod
metadata:
  labels:
    run: webapp
  name: webapp
spec:
  containers:
  - image: kodekloud/event-simulator
    name: webapp1
    volumeMounts:
    - mountPath: /log
      name: webapp-log
  volumes:
  - name: webapp-log
    persistentVolumeClaim:
        claimName: claim-log-1