apiVersion: v1
kind: Service
metadata: 
   name: pod-service
   labels:
    name: nginx
    type: service
spec:
  type: NodePort
  ports:
   - port: 80
     targetPort: 80
     nodePort: 30001
  selector:
    app: nginx