apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: demo-app
    name: postgres-pod-service
spec:
  ports: 
     - port: 5432
       targetPort: 5432
  selector:
    app: demo-app
    name: postgres-pod