apiVersion: v1
kind: Pod
metadata:
  name: readinessProbe-file
  labels:
    name: simple-webapp
spec:
  containers:
  - env:
    - name: APP_START_DELAY
      value: "80"
    image: kodekloud/webapp-delayed-start
    name: simple-webapp
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080
    ports:
    - containerPort: 8080
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300