apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    app: demo-app
    name: result-app-pod
spec:
  containers:
    - name: result-app-pod
      image: kodekloud/examplevotingapp_result:v1
      ports:
        - containerPort: 80