apiVersion: v1
kind: Pod
metadata:
  name: webapp-sample
spec:
  containers:
    - name: webapp-sample
      image: webapp
      envFrom:
#taken from secrets-file.yaml file
        - secretRef:
             name: secret-webapp