apiVersion: v1
kind: Pod
metadata:
   name: redis
   labels:
    name: redis
    app: db
spec:
#describe service account name which need to be mapped with pod to communicate with api-server of k8s
  serviceAccountName: db-redis
  containers:
     - name: redis
       image: redis
       ports:
         - containerPort: 6379