apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: webapp
spec:
#defining toleration which implies only this specific pod can be deployed in the node having same key-value data
  tolerations:
  - key: "app"
    operator: "Equals"
    effect: "NoSchedule"
    value: "blue"
  containers:
    - name: webapp
      image: webapp