apiVersion: v1
kind: Service
metadata:
  name: voting-app-pod-service
  labels:
    app: demo-app
    name: voting-app-pod-service
spec:
  type: NodePort
  ports: 
     - port: 80
       targetPort: 80
       nodePort: 30002
  selector:
    app: demo-app
    name: votingapp