apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
    app: demo-app
    name: votingapp
spec:
  containers:
    - name: voting-app
      image: kodekloud/examplevotingapp_vote:v1
      ports:
        - containerPort: 80