apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    app: demo-app
    name: worker-app-pod
spec:
  containers:
    - name: worker-app-pod
      image: kodekloud/examplevotingapp_worker:v1